apiVersion: v1 # Мы указываем для api сервера, что мы описываем объект из api версии 1
kind: Service # Мы разворачиваем объект типа Сервис
metadata:
  name: svc-nginx-multitool-dz4-node # Имя сервиса
  namespace: dz4
spec:
  ports:
    - name: http-app
      port: 80 # Номер порта, на котором слушает наш сервис
      nodePort: 30000
    - name: http-app-unst
      port: 8080 # Номер порта, на котором слушает наш сервис
      nodePort: 30001

  selector:
    app: web # В селекторе указываем лейбл пода, чтобы он его нашел и подключился
  type: NodePort
