apiVersion: v1 # Мы указываем для api сервера, что мы описываем объект из api версии 1
kind: Service # Мы разворачиваем объект типа Сервис
metadata:
  name: svc-nginx-multitool-dz4 # Имя сервиса
  namespace: dz4
spec:
  ports:
    - name: http-app
      port: 9001 # Номер порта, на котором слушает наш сервис
      protocol: TCP
      targetPort: 80
    - name: http-app-unst
      port: 9002 # Номер порта, на котором слушает наш сервис
      protocol: TCP
      targetPort: 8080
  selector:
    app: web # В селекторе указываем лейбл пода, чтобы он его нашел и подключился
